config/routes.rb
Demo::Application.routes.draw do

  get "paypal_transactions/index"
  get "paypal_transactions_controller/index"
  get 'receipt' => 'paypal_transactions#receipt'
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"
  post 'login' => 'agent_sessions#create'
  get 'login' => 'agent_sessions#new'
  post 'logout' => 'agent_sessions#destroy'
  get 'logout' => 'agent_sessions#destroy'

  get 'account/policies/:policy_id/pay' => 'policies#pay', :as=>'pay'
  post 'account/policies/:policy_id/pay' => 'policies#transaction'

  put 'account/policies/:policy_id/notify' => 'policies#notify', :as=>'notify'

  resource :agent_sessions

  resource :account , :controller=>"agents" do
    resources :policies do
      resources :vehicles, :paypal_transactions
      end
  end

  root 'login#index'

end

app/models/agent.rb
class Agent < ActiveRecord::Base

    acts_as_authentic do |c|
        c.logged_in_timeout = 10.minutes
    end

    validates :first_name, :presence=>true
    validates :last_name, :presence=>true
    validates :email, :presence=>true, :uniqueness=>true, :confirmation=>true
    validates :company, :presence=>true

    validates_format_of :email, :with => Authlogic::Regex.email

    has_many :policies,  dependent: :destroy

    def name
        [first_name, last_name].join " "
    end

end

app/views/agents/_form.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Agent Profile </h3>
    </div>
    <div class="panel-body">

        <%= show_errors(@agent) %>

        <div class="form-group">
            <%= form.label :first_name, "First Name", :class=>'col-sm-2 control-label'%>
            <div class="col-sm-4">
                <%= form.text_field :first_name ,:class=>'form-control'%>
            </div>
        </div>
        <div class="form-group">
            <%= form.label :last_name, "Last Name" ,:class=>'col-sm-2 control-label' %>
            <div class='col-sm-4'>
                <%= form.text_field :last_name, :class=>'form-control'%>
            </div>
        </div>
        <div class="form-group">
            <%= form.label :company , :class=>'col-sm-2 control-label'%>
            <div class='col-sm-4'>
                <%= form.text_field :company, :class=>'form-control'%>
            </div>
        </div>
        <div class='form-group'>
            <%= form.label :email , :class=>'control-label col-sm-2'%>
            <div class='col-sm-4'>
                <%= form.email_field :email , :class=>'form-control', :placeholder=>'example@mail.com'%>
            </div>
        </div>
        <div class='form-group'>
            <%= form.label :email_confirmation,"Confirm Email", :class=>'control-label col-sm-2'%>
            <div class='col-sm-4'>
                <%= form.email_field :email_confirmation, :class=>'form-control' %>
            </div>
        </div>
        <div class='form-group'>
            <%= form.label :password, :class=>'control-label col-sm-2' %>
            <div class='col-sm-4'>
                <%= form.password_field :password, :class=>'form-control'%>
            </div>
        </div>
        <div class='form-group'>
            <%= form.label  :password_confirmation, 'Confirm Password', :class=>'col-sm-2 control-label'%>
            <div class="col-sm-4">
                <%= form.password_field :password_confirmation, :class=>'form-control' %>
            </div>
        </div>
        <div class="form-group">
            <div class='col-sm-4 col-sm-offset-2'>
                <%= form.submit "Submit", :class=>"btn btn-default btn-sm" %>
                <%= link_to "Cancel", :back,  :class=> "btn btn-default btn-sm", :confirm=>"Are you sure?" %>
            </div>
        </div>
    </div>
</div>

app/views/agents/edit.html.erb
<% content_for :title, "Profile" %>
<div class="container">
<%= form_for @agent , :class=>'form-horizontal', :url=>account_path do |f| %>
    <% render :partial => 'form', :object=>f  %>
<% end %>
</div>

app/views/agents/new.html.erb
<% content_for :title, "Agent Registration" %>
<div class="container align-center'">
    <div class='col-lg-8'>
    <%= form_for @agent , :html=>{:class=>'form-horizontal', :role=>'form'}, :url=>account_path do |f| %>
        <%= render :partial => 'form' ,  :object=>f %>
    <% end %>
</div>
</div>

app/views/agents/show.html.erb
<% content_for :title , "Account" %>
<div class="container">
    <div class="panel panel-success">
        <div class="panel-heading">
        <h3><%= "#{@agent.first_name}  #{@agent.last_name}" %> <%= link_to "Edit", edit_account_path, :class=>"btn btn-link" %></h3>
        </div>
        <div class="panel-body">
        <div class="row">
        <div class="col-md-3">
            <strong>Company </strong>
            <%= @agent.company %>
        </div>
        <div class="col-md-3">
            <strong>Email </strong>
            <%= @agent.email %>
        </div>
    </div>
    </div>
    </div>
</div>
<div class="container">
    <div class="panel panel-default">
        <div class='panel-heading'>
            <h3>Policies <%= link_to "Add Policy", new_account_policy_path, :class=>"btn btn-link" %></h3>
        </div>
        <div class="panel-body">
            <%= render :partial=>"policies/policies", :object=>@agent %>
        </div>
</div> <!-- container -->