config/routes.rb
Demo::Application.routes.draw do

  get "paypal_transactions/index"
  get "paypal_transactions_controller/index"
  get 'receipt' => 'paypal_transactions#receipt'
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"
  post 'login' => 'agent_sessions#create'
  get 'login' => 'agent_sessions#new'
  post 'logout' => 'agent_sessions#destroy'
  get 'logout' => 'agent_sessions#destroy'

  get 'account/policies/:policy_id/pay' => 'policies#pay', :as=>'pay'
  post 'account/policies/:policy_id/pay' => 'policies#transaction'

  put 'account/policies/:policy_id/notify' => 'policies#notify', :as=>'notify'

  resource :agent_sessions

  resource :account , :controller=>"agents" do
    resources :policies do
      resources :vehicles, :paypal_transactions
      end
  end

  root 'login#index'

end

app/models/vehicle.rb
require 'paypal_transaction'

class Vehicle < ActiveRecord::Base

    # Flat percentage rate applied to deductible.
    # Not sure what we want for this value.
    RATE = 0.10

    validates :vin, :presence=>true
    validates :make, :presence=>true
    validates :model, :presence=>true
    validates :color, :presence=>true
    validates :year, :presence=>true
    validates :deductible, :presence=>true

    belongs_to :policy

    # Returns true if the end_date is after Date.today else false if
    # end_date is nil or before Date.today.
    def covered?
        unless expr_date.nil?
            return ((expr_date<=>Date.today )> 0 ) ? true : false
        end
        false
    end

    # Returns the cost of coverage for the vehicle
    def cost
        deductible * RATE
    end
end

app/controllers/vehicles_controller.rb
require 'pay_pal_helper'
require_dependency 'payment_info'

class VehiclesController < ApplicationController

    before_filter :require_user, :except=>[:pay, :transaction]

    LOGGER_TAG ="VehiclesController::"

    def new
        @vehicle = Vehicle.new
    end

    def create
        logger.debug("#{LOGGER_TAG}create >> #{params.inspect}")
        @policy = Policy.find(params[:policy_id])
        @vehicle = @policy.vehicles.build(vehicle_params)
        # This is where we could check to make sure we get at least
        # one vehicle defined.
        logger.debug("#{LOGGER_TAG}create #{@policy.inspect}")
        logger.debug("#{LOGGER_TAG}reate #{@vehicle.inspect}")

        if @vehicle.save
            flash[:notice] = "Successfully added a new vechicle."
            redirect_to account_policy_path(params[:policy_id])
        else
            render :action=> 'new'
        end
    end

    def show
        @vehicle = Vehicle.find(params[:id])
    end

    def edit
        @vehicle = Vehicle.find(params[:id])
    end

    def update
        logger.debug("#{LOGGER_TAG} update")
        @vehicle = Vehicle.find(params[:id])
        if @vehicle.update(vehicle_params)
            flash[:notice] = "Sucessfully updated vehicle information."
            render :action => 'show'
        else
            render :action => 'edit'
        end
    end

    def destroy
        logger.debug "#{LOGGER_TAG}destroy"
        @vehicle = Vehicle.find(params[:id])
        if @vehicle.destroy
            flash[:notice] = "Successfully removed vehicle."
        end

        redirect_to account_policy_path(params[:policy_id])
    end

    private
        def vehicle_params
            params.require(:vehicle).permit(:vin,
                :make,
                :model,
                :color,
                :deductible,
                :previous_deductible,
                :drivers,
                :year)
        end
end

app/views/vehicles/_vehicle_view.html.erb
<div class="container">
<div class="row">
    <div class="span4">
        <strong>VIN </strong>
        <%= v.vin %>
    </div>
    <div class="span4">
        <strong>Make </strong>
        <%= v.make %>
    </div>
    <div class="span4">
        <strong>Model </strong>
        <%= v.model %>
    </div>
    <div class='span4'>
        <strong>Year </strong>
        <%= v.year %>
    </div>
    <div class="span4">
        <strong>Color </strong>
        <%= v.color %>
    </div>
    <div class="span4">
        <strong>Drivers</strong>
        <%= v.drivers %>
    </div>
</div>

</br>
<div class="row">
    <div class="span12">
        <h3>Coverage Information</h3>
    </div>
</div>

<div class="row">
    <div class="span4">
        <strong>Start  </strong>
        <% if  v.start_date %>
            <%= v.start_date.to_s(:long) %>
        <% end %>
    </div>
    <div class="span4">
        <strong>Expires </strong>
        <% if v.expr_date %>
            <%= v.expr_date.to_s(:long) %>
        <% end %>
    </div>
    <div class="span4">
        <strong>Deductible $</strong>
        <%= v.deductible %>
    </div>
</div>
</div>

app/views/vehicles/_vehicles.html.erb
    <%if @policy.vehicles.count > 0 %>
            <% if @policy.not_covered.count > 0 %>

                    <div class="alert alert-warning">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <strong>Warning!</strong> One or more deductibles are not currently covered. <%= link_to "Send Reminder..", notify_path(@policy.id), :class=>"btn btn-link", :method=>:put %>
                    </div>


            <% end %>

            <div class='table-responsive'>
                <table class="table table-striped table-condensed">
                    <tr>
                        <th>Vin</th>
                        <th>Make</th>
                        <th>Model</th>
                        <th>Deductible</th>
                        <th>Status</th>
                    </tr>
                    <% @policy.vehicles.each do |v| %>
                    <tr>
                        <td><%= link_to raw("<span class='glyphicon glyphicon-remove red'></span>"), account_policy_vehicle_path(@policy.id, v.id),
                                :method=>:delete, :data=>{:confirm=>"Are you sure you want to remove this vehicle?"} %>
                                <%= link_to v.vin, account_policy_vehicle_path(v.policy_id, v.id) %></td>
                        <td><%= v.make %></td>
                        <td><%= v.model %></td>
                        <td><%= "$ #{'%.2f' % v.deductible}" %></td>
                        <% if v.covered? %>
                            <td>OK</td>
                        <% else %>
                            <td>Needs Attention</td>
                        <% end %>
                    </tr>
                    <% end %>
                </table>
            </div>

    <% else %>
        <div class='row'>
            <p>The policy does not have any vehicles covered at this time.</p>
        </div>
    <% end %>

app/views/vehicles/_vehicles_mini.html.erb
<fieldset>
    <div class="form-group">
        <%= form.label :vin, "VIN", :class=>"col-md-2 control-label" %>
        <div class="col-md-10">
            <%= form.text_field :vin, :class=>"form-control" %>
        </div>
    </div>
    <div class="form-group">
        <%= form.label :drivers , :class=>"col-md-2 control-label" %>
        <div class="col-md-10">
            <%= form.text_field :drivers, :placeholder=>"John Doe, Jane Doe" , :class=>"form-control"%>
        </div>
    </div>
    <div class="form-group">
        <%= form.label :make, :class=>"col-md-2 control-label"%>
        <div class="col-md-10">
            <%= form.text_field :make , :class=>"form-control"%>
        </div>
    </div>
    <div class="form-group">
        <%= form.label :model, :class=>"col-md-2 control-label"%>
        <div class="col-md-10">
            <%= form.text_field :model, :class=>"form-control" %>
        </div>
    </div>
    <div class="form-group">
        <%= form.label :year , :class=>"col-md-2 control-label"%>
        <div class="col-md-10">
            <%# This is because we are using the same form for new and edit %>
             <% year = Date.today %>
            <% unless @vehicle.nil? || @vehicle.year.nil?  %>
                <% year = @vehicle.year %>
            <% end %>
            <%= select_year(year, {:start_year=>1930, :end_year=>Date.today.year}, {:class=>'form-control', :id=>'vehicle_year', :name=>selectid}) %>
        </div>
    </div>
    <div class="form-group">
        <%= form.label :color , :class=>"col-md-2 control-label"%>
        <div class="col-md-10">
            <%= form.text_field :color, :class=>"form-control" %>
        </div>
    </div>
    <div class="form-group">
        <%= form.label :deductible, :class=>"col-md-2 control-label" %>
        <div class='input-group col-md-10'>
            <span class="input-group-addon">$</span>
            <%= form.text_field :deductible , :class=>"form-control money"%>
            <span class="input-group-addon">.00</span>
        </div>
    </div>
    <div class="form-group">
        <%= form.label :previous_deductible,  'Previous Deductible' , :class=>"col-md-2 control-label" %>
        <div class="col-md-10 input-group">
            <span class="input-group-addon">$</span>
            <%= form.text_field :previous_deductible, :class=>"form-control money"%>
            <span class="input-group-addon">.00</span>
        </div>
    </div>
</fieldset>

app/views/vehicles/edit.html.erb
<% content_for :title, 'Edit Vehicle' %>
<div class="container">
    <div class='panel panel-default'>
        <div class='panel-heading'>
            <h3>Edit Vehicle</h3>
        </div>
        <div class='panel-body'>
            <%= form_for @vehicle , :url=>account_policy_vehicle_path do |f| %>
                <%= show_errors(@vehicle) %>
                <%= render :partial=>'vehicles_mini' , :locals=>{:form=>f, :selectid=>'vehicle[year]'} %>
                <%= f.submit 'Submit', :class=>'btn btn-default' %>
                <%= link_to 'Cancel', :back, :class=>'btn btn-default', :confirm=>"Are you sure?" %>
            <% end %>
        </div>
    </div>
</div>

app/views/vehicles/new.html.erb
<% content_for :title, 'New Vehicle' %>

<div class='container'>
    <div class="panel panel-default">
        <div class='panel-heading'>
            <h3>New Vehicle</h3>
        </div>
        <div class='panel-body'>
            <%= form_for @vehicle, :url=>account_policy_vehicles_path do |f| %>
                <%= show_errors(@vehicle) %>
                <%= render :partial=>'vehicles_mini', :locals=>{:form=>f , :selectid=>'vehicle[year]'} %>
                <%= f.submit 'Submit', :class=>'btn btn-default' %>
                <%= link_to 'Cancel', :back, :class=>'btn btn-default', :confirm=>"Are you sure?" %>
            <% end %>
        </div>
    </div>
</div>

app/views/vehicles/show.html.erb
<% content_for :title=>"Vehicle" %>

<div class="container">
    <div class='panel panel-success'>
        <div class='panel-heading'>
            <h3>Vehicle Information
                <%= link_to "Edit", edit_account_policy_vehicle_path(@vehicle.policy_id, @vehicle.id) , :class=>"btn btn-link" %>
                <%= link_to "Policy", account_policy_path(@vehicle.policy_id), :class=>"btn btn-link"%>
            </h3>
        </div>
        <div class='panel-body'>
            <%= render :partial=>'vehicle_view', :locals=>{:v=>@vehicle} %>
        </div>
    </div>
</div>