config/routes.rb
Demo::Application.routes.draw do

  get "paypal_transactions/index"
  get "paypal_transactions_controller/index"
  get 'receipt' => 'paypal_transactions#receipt'
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"
  post 'login' => 'agent_sessions#create'
  get 'login' => 'agent_sessions#new'
  post 'logout' => 'agent_sessions#destroy'
  get 'logout' => 'agent_sessions#destroy'

  get 'account/policies/:policy_id/pay' => 'policies#pay', :as=>'pay'
  post 'account/policies/:policy_id/pay' => 'policies#transaction'

  put 'account/policies/:policy_id/notify' => 'policies#notify', :as=>'notify'

  resource :agent_sessions

  resource :account , :controller=>"agents" do
    resources :policies do
      resources :vehicles, :paypal_transactions
      end
  end

  root 'login#index'

end

app/views/layouts/_messages.html.erb
<div class="container">

        <div class="col-lg-4 col-md-offset-4">
            <% flash.each do |name, msg| %>
                <% if msg.is_a?(String) %>
                <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
                <a class="close" data-dismiss="alert">&#215;</a>
                    <%= content_tag :div, msg, :id => "flash_#{name}" %>
                </div>
                <% end %>
          <% end %>
      </div>

</div><!-- container -->

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to "Company Name", root_path, :class=>"navbar-brand" %>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="/">Home</a></li>
                <li><%= link_to "About", about_path %></li>
                <li><%= link_to "Contact", contact_path %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <% if current_user %>
                <li>
                    <%= link_to "Account", account_path  %>
                </li>
                <li>
                    <%= link_to "Logout", logout_path , :data=>{:confirm=>"You sure?"}  %>
                </li>
                <% else %>
                <li>
                    <%= link_to "Register", new_account_path %>
                </li>
                <li>
                    <%= link_to "Login", login_path %>
                </li>
                <% end %>
            </ul>
        </div>
    </div>
</div>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Company Name</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Home', root_path %></li>
            <li><%= link_to 'About', about_path %></li>
            <li><%= link_to 'Contact', contact_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li>
                <%= link_to "Account", account_path  %>
              </li>
              <li>
                <%= link_to "Logout", logout_path , :data=>{:confirm=>"You sure?"}  %>
              </li>
          </ul>
            <% else %>
              <li>
                <%= link_to "Register", new_account_path %>
              </li>
          </ul>
              <%= form_for  a = AgentSession.new, :html=>{:class=>"navbar-form navbar-right"} do |f|%>
              <%= show_errors(a) %>
                <div class="form-group">
                  <%= f.email_field :email, :placeholder=>"Email", :class=>"form-control input-sm"%>
                </div>
                <div class="form-group">
                  <%= f.password_field :password, :placeholder=>"Password", :class=>"form-control input-sm" %>
                </div>
                <button type="submit" class="btn btn-success btn-sm">Sign in</button>
              </form>
              <% end %>
            <% end %>
        </div><!--/.navbar-collapse -->
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Insurance Demo" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Bootstrap" %>">
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>
  <%= yield %>


<footer>
  <hr>
    <p>&copy; Company Name 2013</p>
</footer>
</body>



</html>