config/routes.rb
Demo::Application.routes.draw do

  get "paypal_transactions/index"
  get "paypal_transactions_controller/index"
  get 'receipt' => 'paypal_transactions#receipt'
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"
  post 'login' => 'agent_sessions#create'
  get 'login' => 'agent_sessions#new'
  post 'logout' => 'agent_sessions#destroy'
  get 'logout' => 'agent_sessions#destroy'

  get 'account/policies/:policy_id/pay' => 'policies#pay', :as=>'pay'
  post 'account/policies/:policy_id/pay' => 'policies#transaction'

  put 'account/policies/:policy_id/notify' => 'policies#notify', :as=>'notify'

  resource :agent_sessions

  resource :account , :controller=>"agents" do
    resources :policies do
      resources :vehicles, :paypal_transactions
      end
  end

  root 'login#index'

end

app/models/policy.rb
class Policy < ActiveRecord::Base

    validates :first_name,  :presence=>true
    validates :last_name, :presence=>true
    validates :address, :presence=>true
    validates :city, :presence=>true
    validates :state, :presence=>true
    validates :zip_code, :presence=>true
    validates :number, :presence=>true, :uniqueness=>true
    validates :email, :presence=>true, :confirmation=>true
    validates :email_confirmation, :presence=>true



    belongs_to :agent
    has_many :vehicles, dependent: :destroy
    has_many :paypal_transactions

    accepts_nested_attributes_for :vehicles, :reject_if=> proc {
     |attributes| attributes['vin'].blank? and
            attributes['make'].blank? and
            attributes['model'].blank? and
            attributes['color'].blank?  and
            attributes['deductible'].blank? and
            attributes['drivers'].blank?
        }

    validates_associated :vehicles

    #Returns true if all the vehicles within the policy are currently covered,
    #else returns false
    def up_to_date?
        return not_covered.count > 0 ? false : true
    end

    # Returns of a list of vehicles within the policy that
    # have expired coverage.
    def not_covered
        items = Array.new

        vehicles.each do |v|
            unless v.covered?
                items << v
            end
        end

        items
    end

    # Calculates the total coverage cost outstanding for the policy.
    # Basically iterates over the non-covered vehicles and sums eache
    # individual vehicle coverage cost.
    def cost
        total = 0.0
        not_covered.each do |n|
            total += n.cost
        end
        total
    end
end

app/controllers/policies_controller.rb
class PoliciesController < ApplicationController

    before_filter :require_no_user, :only=>:pay

    def new
        @policy = Policy.new
        2.times{@policy.vehicles.build}
    end

    def create
        @agent = current_user
        @policy = @agent.policies.build(policy_params)
        if @policy.save
                # This is where it gets wierd. We need to send out and email
                # if  we have vehicles since the policy doesn't contain any information
                # to build a payment transaction off of.
                # It is not mandatory to add at least one vehicle during registration, but I
                # think it probably should be.
                unless @policy.vehicles.nil? || @policy.vehicles.count == 0
                    logger.debug 'PoliciesController::Got some vehicles, sending out an email.'
                    ClientMailer.notify_policy(@policy, request).deliver
                end
                redirect_to account_url
        else
            render :action => 'new'
        end
    end

    def edit
        @policy = Policy.find(params[:id])
    end

    def show
        @policy = Policy.find(params[:id])
    end

    def update
        @policy = Policy.find(params[:id])
        if @policy.update(policy_params)
            render :action=>'show'
        else
            render :action =>'edit'
        end
    end

    def destroy
        @policy = Policy.find(params[:id])
        @policy.destroy

        redirect_to account_url
    end

    def pay
        logger.debug("Pay<< params = #{params.inspect}")
        @policy = Policy.find(params[:policy_id])
        @payment_info = PaymentInfo.new
    end

    def transaction
        logger.debug("PolicyController::<< Params= #{params.inspect}")
        @policy = Policy.find(params[:policy_id])
        @payment_info = PaymentInfo.new(params[:payment_info])
        if @payment_info.valid?
            logger.debug("PolicyController::payment_info is valid.")
           @paypal = PayPalHelper.new(@payment_info, @policy)

           if @paypal.make_payment
                render 'paypal_transactions/receipt'
           else
                @payment_info.error = @paypal.error
                render :action=>'pay'
            end
        else
            render :action=>'pay'
        end
    end

    def notify
        logger.debug "PolicyController::notify <<<"
        @policy= Policy.find(params[:policy_id])
        mail = ClientMailer.notify_policy(@policy, request).deliver
        logger.debug "sent mail #{mail.inspect}"
        flash[:notice] = "Sent an email reminder to the policy holder."
        redirect_to account_policy_path(params[:policy_id])
    end

    private
        def policy_params
            params.require(:policy).permit(
                :number,  :first_name, :last_name, :email, :email_confirmation,
                :address, :city, :state, :zip_code, vehicles_attributes:
                [ :id, :vin, :make, :model, :color, :deductible, :previous_deductible, :year, :drivers])
        end
end

app/views/policies/_form.html.erb
<fieldset>
    <%= show_errors(@policy) %>
    <div class="form-group">
            <%= form.label :number,  'Policy Number', :class=>"col-md-2 control-label" %>
        <div class='col-md-10'>
            <%= form.text_field :number , :class=>"form-control" %>
        </div>
    </div>
    <div class="form-group">
            <%= form.label :first_name, "First Name" , :class=>"col-md-2 control-label"%>
        <div class="col-md-10">
            <%= form.text_field :first_name, :class=>"form-control" %>
        </div>
    </div>
    <div class="form-group">
            <%= form.label :last_name, "Last Name" , :class=>"col-md-2 control-label"%>
            <div class="col-md-10">
                <%= form.text_field :last_name, :class=>"form-control" %>
            </div>
    </div>
    <div class="form-group">
            <%= form.label :email, :class=>"col-md-2 control-label" %>
            <div class="col-md-10">
                <%= form.email_field :email , :class=>"form-control" %>
            </div>
    </div>
    <div class="form-group">
            <%= form.label :email_confirmation, "Confirm Email", :class=>"col-md-2 control-label" %>
        <div class="col-md-10">
            <%= form.email_field :email_confirmation, :class=>"form-control"%>
        </div>
    </div>
    <div class="form-group">
            <%= form.label :address, :class=>'col-md-2  control-label' %>
            <div class="col-md-10">
                <%= form.text_field :address, :class=>"form-control" %>
            </div>
    </div>
    <div class="form-group">
            <%= form.label :city , :class=>"col-md-2 control-label"%>
        <div class="col-md-10">
            <%= form.text_field :city, :class=>"form-control" %>
        </div>
    </div>
    <div class="form-group">
            <%= form.label :state, :class=>"col-md-2 control-label" %>
        <div class="col-md-10">
            <%= form.text_field :state, :class=>"form-control" %>
        </div>
    </div>
    <div class="form-group">
            <%= form.label :zip_code, "Zip Code", :class=>"col-md-2 control-label" %>
        <div class="col-md-10">
            <%= form.text_field :zip_code, :class=>"form-control" %>
        </div>
    </div>
</fieldset>

app/views/policies/_policies.html.erb
<%if @agent.policies %>
    <div class='table-responsive'>
        <table class="table table-striped table-condensed">
            <tr>
                <th>Policy</th>
                <th>Holder</th>
                <th>Vehicles</th>
                <th>Status</th>
            </tr>
            <% @agent.policies.each do |p| %>
            <tr>
                <td><%= link_to raw("<i class='glyphicon glyphicon-remove red'></i>") , account_policy_path(p.id),
                        :method=>:delete, :data=>{:confirm=>"Are you sure you want to remove this policy?"}%>
                        <%= link_to p.number, account_policy_path(p.id) %></td>
                <td><%= p.last_name %></td>
                <td><%= p.vehicles.count %></td>
                <% if p.not_covered.count > 0 %>
                    <td>Needs Attention </td>
                <% else %>
                    <td>OK</td>
                <% end %>
            </tr>
            <% end %>
        </table>
    </div>
<% else %>
    <p>You don't have any policies at this time.</p>
<% end %>

app/views/policies/edit.html.erb
<% content_for :title, "Edit Policy" %>
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>Edit Policy</h3>
        </div>
        <div class="panel-body">
            <%= form_for @policy, :url=>account_policy_path do |f| %>
                <%= render :partial=>'form', :object=>f %>
                <div class="form-group">
                    <div class="col-lg-10 col-offset-2">
                        <%= f.submit 'Submit', :class=>'btn btn-default btn-sm' %>
                        <%= link_to 'Cancel', account_policy_path, :class=>'btn btn-default btn-sm', :confirm=>"Are you sure?" %>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/policies/new.html.erb
<% content_for :title, "New Policy" %>
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>New Policy</h3>
        </div>
        <div class="panel-body">
            <%= form_for @policy, :url=>account_policies_path do |f| %>
            <%= render :partial=>'form', :object=>f %>
            <% count = 0 %>
            <%= f.fields_for :vehicles  do |vehicles| %>
                <div class="row">
                    <div class="col-md-2">
                        <h3>Vehicle <%= count += 1 %> </h3>
                        <hr>
                    </div>
                </div>
                <%= render :partial=>'vehicles/vehicles_mini', :locals=>{:form=>vehicles, :selectid=>"policy[vehicles_attributes][#{count-1}][year]"} %>
            <% end %>

            <%= f.submit 'Submit', :class=>'btn btn-default btn-small' %>
            <%= link_to 'Cancel', account_path, :class=>'btn btn-default btn-small', :confirm=>"Are you sure?" %>
            <% end %>
        </div>
    </div>
</div>

app/views/policies/pay.html.erb
<div class="container">
    <div class='panel panel-success'>
        <div class='panel-heading'>
            <h3>Deductible Coverage</h3>
        </div>
        <div class='panel-body'>
            <% up_to_date = @policy.up_to_date? %>
            <% if up_to_date %>
                <p> All the vehicles within the policy <%= @policy.number %> currently have deductible coverage. No action required at this time. Thanks!</p>
            <% else %>
                <p>
                    The following vehicles are due for deductible coverage activation. Use the form below to securely pay for another year of deductible coverage.
                </p>
                <br/>
                <% if @policy.not_covered.count > 0 %>
                    <table id='vehicle_table' class='table'>
                        <tr>
                            <th>VIN</th>
                            <th>Make</th>
                            <th>Expires</th>
                            <th>Deductible</th>
                            <th>Coverage</th>
                        </tr>

                        <%  @policy.not_covered.each do |v| %>
                                <tr>
                                    <td><%= v.vin %></td>
                                    <td><%= v.make %></td>
                                    <td><%= v.expr_date ? v.expr_date : 'Not Activated' %>
                                    <td>$ <%= '%.2f' % v.deductible %></td>
                                    <td class='text-align-right'>$ <%= '%.2f' % (v.cost) %> </td>
                                </tr>
                        <% end %>

                        <tr>
                            <td> </td>
                            <td> </td>
                            <td> </td>
                            <td>Total</td>
                            <td>$ <%= '%.2f' % @policy.cost %></td>
                        </tr>
                    </table>
                <% end %>
          <% end %>
        </div>
    </div>

    <% if not up_to_date %>
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3>Billing Information</h3>
            </div>
            <div class="panel-body">
                <div class='row'>
                    <div class='col-md-12'>
                        <%= show_errors(@payment_info) %>
                    </div>
                <div class='container'>
                    <div class='col-md-12'>
                        <% if @payment_info.error %>
                            <div clas="row">
                                  <div id="error_explanation" class='alert alert-danger'>
                                    <strong>Oh Snap!</strong> Change some things up and submit again.
                                    <ul>
                                        <%= @payment_info.error %>
                                    </ul>
                                  </div>
                            </div>
                        <% end %>
                    </div>
                </div>
                    <%= form_for @payment_info , :url=>pay_path , :html=>{:class=>'form-horizontal'} ,:method=>'post' do |f| %>
                        <div class='form-group'>
                            <%= f.label :amount, "Amount $" , :class=>'col-md-2 control-label'%>
                            <div class='col-md-4'>
                                <%= f.text_field :amount,  :value=>'%.2f' % (@policy.cost + (@policy.cost * 0.08)), :readonly=>true, :class=>'form-control money'%>
                            </div>
                            <div class='col-md-2'>
                                *Tax Included
                             </div>
                        </div>
                        <div class='form-group'>
                            <%= f.label :first_name, 'First Name', :class=>'control-label col-md-2' %>
                            <div class='col-md-4'>
                                <%= f.text_field :first_name, :value=>@policy.first_name, :class=>'form-control' %>
                            </div>
                        </div>
                        <div class='form-group'>
                            <%= f.label :last_name , 'Last Name', :class=>'control-label col-md-2'%>
                            <div class='col-md-4'>
                                <%= f.text_field :last_name,  :value=>@policy.last_name, :class=>'form-control' %>
                            </div>
                        </div>

                    <div class='form-group'>
                        <%= f.label :address , :class=>'control-label col-md-2'%>
                        <div class='col-md-4'>
                            <%= f.text_field :address, :value=>@policy.address, :class=>'form-control' %>
                        </div>
                    </div>
                    <div class='form-group'>
                        <%= f.label :city, :class=>'control-label col-md-2' %>
                        <div class='col-md-4'>
                            <%= f.text_field :city, :value=>@policy.city, :class=>'form-control' %>
                        </div>
                    </div>
                    <div class='form-group'>
                        <%= f.label :state, :class=>'control-label col-md-2' %>
                        <div class='col-md-4'>
                            <%= f.text_field :state, :value=>@policy.state, :class=>'form-control' %>
                        </div>
                    </div>
                    <div class='form-group'>
                        <%= f.label :zip_code, 'Zip Code', :class=>'control-label col-md-2' %>
                        <div class='col-md-4'>
                            <%= f.text_field :zip_code , :value=>@policy.zip_code, :class=>'form-control' %>
                        </div>
                    </div>

                    <%# Credit Card Info is hard-coded for right now %>
                    <div class='form-group'>
                        <%= f.label :card_type, 'Card Type', :class=>'control-label col-md-2' %>
                        <div class='col-md-4'>
                            <%= f.select :card_type, [['Visa', 'visa'], ['MasterCard', 'mastercard']], {:readonly=>true, :selected=>'mastercard'},  {:class=>'form-control disabled' } %>
                        </div>
                    </div>
                    <div class='form-group'>
                        <%= f.label :card_number , 'Card Number',  :class=>'control-label col-md-2'%>
                        <div class='col-md-4'>
                            <%= f.text_field :card_number, :readonly=>:true, :value=>'5500005555555559', :class=>'form-control' %>
                        </div>
                    </div>
                    <div class='form-group'>
                        <%= f.label :cvv2, 'CVV2', :class=>'control-label col-md-2' %>
                        <div class='col-md-1'>
                            <%= f.text_field :cvv2, :readonly=>true, :value=>'111', :class=>'form-control'%>
                        </div>
                    </div>
                    <div class='form-group'>
                        <%= f.label :expr_month , :class=>'control-label col-md-2' %>
                        <div class='col-md-4'>
                            <%= select_month(Date.today, {:use_month_numbers=>true}, {:class=>'form-control', :id=>'payment_info_expr_month', :name=>'payment_info[expr_month]'}) %>
                        </div>
                    </div>
                    <div class='form-group'>
                        <%= f.label :expr_year , :class=>'control-label col-md-2' %>
                        <div class='col-md-4'>
                            <%= select_year(Date.today, {:end_year=>Date.today.year + 10}, {:class=>'form-control', :id=>'payment_info_expr_year', :name=>'payment_info[expr_year]'}) %>
                        </div>
                    </div>
                    <%= submit_tag 'Pay Now', :class=>'btn btn-default col-md-offset-2' %>
                    <%= link_to 'Cancel', :root , :data=>{:confirm=>'Are you sure you want to cancel this transaction?'} , :class=>'btn btn-default' %>
                    <% end %>

            </div>
            </div>
        <% end %>
    </div>

app/views/policies/show.html.erb
<% content_for :title=>"Policy" %>
<div class="container">
    <div class="panel panel-success">
        <div class="panel-heading">
            <h4><%= "Policy -  #{@policy.number}" %>
                <%= link_to "All Policies", account_path, :class=>"btn btn-link" %>
                <%= link_to "Edit", edit_account_policy_path, :class=>"btn btn-link" %>
                <%= link_to "Billing History",account_policy_paypal_transactions_path(@policy.id), :class=>"btn btn-link" %>
                <%= link_to "Remove Policy", account_policy_path, :class=>"btn btn-link",
                :method=> :delete , :data=>{:confirm=>"Are you sure you want to remove this policy?"} %>
            </h4>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class='col-md-4'>
                    <strong>Holder </strong><span></span>
                    <%= "#{@policy.first_name} #{@policy.last_name}" %>
                </div>
                <div class="col-md-4">
                    <strong>Email </strong>
                    <%= @policy.email %>
                </div>
                <div class="col-md-4">
                    <strong>Address </strong>
                    <%= "#{@policy.address}, #{@policy.city}, #{@policy.state}, #{@policy.zip_code}" %>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4>Vehicles <%= link_to "Add Vehicle", new_account_policy_vehicle_path(@policy.id), :class=>"btn btn-link" %></h4>
        </div>
        <div class="panel-body">
            <%= render :partial=>"vehicles/vehicles", :object=>@policy %>
        </div>
    </div>
</div>